# Generated by Django 6.0.2 on 2026-03-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_recipeingredient_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ledger.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default='2026-02-03T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
