# Generated by Django 6.0.2 on 2026-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_author_recipe_createdon_recipe_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
