# Generated by Django 6.0.2 on 2026-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipe_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
